import { UsageResponse } from "../types/usage"

// Mock data for screenshot purposes with latest AI models (as of Feb 2026)
// Models from: https://docs.github.com/en/copilot/reference/ai-models/supported-models
export const mockUsageData: Record<string, UsageResponse> = {
    low: {
        timePeriod: {
            year: 2026,
            month: 2,
        },
        user: "octocat",
        usageItems: [
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "gpt-4.1",
                unitType: "requests",
                pricePerUnit: 0.01,
                grossQuantity: 40,
                grossAmount: 0.4,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 40,
                netAmount: 0.4,
            },
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "claude-sonnet-4.5",
                unitType: "requests",
                pricePerUnit: 0.015,
                grossQuantity: 25,
                grossAmount: 0.375,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 25,
                netAmount: 0.375,
            },
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "gemini-2.5-pro",
                unitType: "requests",
                pricePerUnit: 0.015,
                grossQuantity: 15,
                grossAmount: 0.225,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 15,
                netAmount: 0.225,
            },
        ],
    },
    medium: {
        timePeriod: {
            year: 2026,
            month: 2,
        },
        user: "octocat",
        usageItems: [
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "gpt-5.1",
                unitType: "requests",
                pricePerUnit: 0.02,
                grossQuantity: 110,
                grossAmount: 2.2,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 110,
                netAmount: 2.2,
            },
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "claude-sonnet-4.5",
                unitType: "requests",
                pricePerUnit: 0.015,
                grossQuantity: 80,
                grossAmount: 1.2,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 80,
                netAmount: 1.2,
            },
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "claude-opus-4.5",
                unitType: "requests",
                pricePerUnit: 0.05,
                grossQuantity: 20,
                grossAmount: 1.0,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 20,
                netAmount: 1.0,
            },
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "gemini-3-pro",
                unitType: "requests",
                pricePerUnit: 0.015,
                grossQuantity: 35,
                grossAmount: 0.525,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 35,
                netAmount: 0.525,
            },
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "gpt-5.1-codex-mini",
                unitType: "requests",
                pricePerUnit: 0.01,
                grossQuantity: 25,
                grossAmount: 0.25,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 25,
                netAmount: 0.25,
            },
        ],
    },
    high: {
        timePeriod: {
            year: 2026,
            month: 2,
        },
        user: "octocat",
        usageItems: [
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "gpt-5.2",
                unitType: "requests",
                pricePerUnit: 0.02,
                grossQuantity: 145,
                grossAmount: 2.9,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 145,
                netAmount: 2.9,
            },
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "claude-sonnet-4.5",
                unitType: "requests",
                pricePerUnit: 0.015,
                grossQuantity: 50,
                grossAmount: 0.75,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 50,
                netAmount: 0.75,
            },
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "claude-opus-4.5",
                unitType: "requests",
                pricePerUnit: 0.05,
                grossQuantity: 30,
                grossAmount: 1.5,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 30,
                netAmount: 1.5,
            },
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "gemini-3-pro",
                unitType: "requests",
                pricePerUnit: 0.015,
                grossQuantity: 25,
                grossAmount: 0.375,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 25,
                netAmount: 0.375,
            },
            {
                product: "GitHub Copilot",
                sku: "GITHUB_COPILOT_MONTHLY",
                model: "gpt-5.1-codex",
                unitType: "requests",
                pricePerUnit: 0.02,
                grossQuantity: 35,
                grossAmount: 0.7,
                discountQuantity: 0,
                discountAmount: 0,
                netQuantity: 35,
                netAmount: 0.7,
            },
        ],
    },
}
